@startuml editarDocente-analisis
skinparam linetype polyline

actor AdministradorInstitucional
package editarDocente as "editarDocente()" {
    rectangle #629EF9 DocenteEditView
    rectangle #b5bd68 DocenteController
    rectangle #F2AC4E Docente
}

AdministradorInstitucional -r-> DocenteEditView: modificarDatos(datos)
DocenteEditView -d-> DocenteController: guardar(datos)
DocenteController --> Docente: actualizar(datos)

AdministradorInstitucional --> DocenteEditView: eliminarDocente()
DocenteEditView --> DocenteController: eliminar()
DocenteController --> Docente: delete()

@enduml
