@startuml importarConfiguracionGlobal-analisis
skinparam linetype polyline

actor Docente
package importarConfiguracionGlobal as "importarConfiguracionGlobal()" {
    rectangle #629EF9 VistaImportConfigGlobal
    rectangle #b5bd68 ControladorImportacion
    rectangle #F2AC4E ConfiguracionGlobal
    rectangle #F2AC4E Alumno
    rectangle #F2AC4E Grado
    rectangle #F2AC4E Asignatura
    rectangle #F2AC4E Pregunta
}

Docente -r-> VistaImportConfigGlobal: importarConfiguracion(archivo, opciones)
VistaImportConfigGlobal -d-> ControladorImportacion: procesarImportacion(archivo, opciones)
ControladorImportacion --> ConfiguracionGlobal: extraerDatos()
ControladorImportacion --> VistaImportConfigGlobal: mostrarValidacion()

Docente --> VistaImportConfigGlobal: confirmarImportacion()
VistaImportConfigGlobal --> ControladorImportacion: persistirCambios()

ControladorImportacion --> Alumno: guardar()
ControladorImportacion --> Grado: guardar()
ControladorImportacion --> Asignatura: guardar()
ControladorImportacion --> Pregunta: guardar()

@enduml