@startuml importarGrados-analisis
skinparam linetype polyline

actor Docente
package importarGrados as "importarGrados()" {
    rectangle #629EF9 VistaImportacionGrados
    rectangle #b5bd68 ControladorImportacionGrados
    rectangle #F2AC4E Grado
}

Docente -r-> VistaImportacionGrados: solicitarImportar()
VistaImportacionGrados --> Docente: pedirOrigen()
Docente --> VistaImportacionGrados: proporcionarOrigen()
VistaImportacionGrados --> ControladorImportacionGrados: validarIntegridad()
ControladorImportacionGrados --> Grado: verificarDuplicados()
VistaImportacionGrados --> Docente: pedirConfirmacion()
Docente --> VistaImportacionGrados: confirmar()
VistaImportacionGrados -d-> ControladorImportacionGrados: ejecutarImportacion()
ControladorImportacionGrados --> Grado: createAll()

@enduml