@startuml cu39-importarGrados-analisis-secuencia
title Diagrama de Secuencia (Análisis) - CU-39: Importar Grados

participant ":VistaImportacionGrados" as Boundary <<boundary>>
participant ":ControladorImportacionGrados" as Control <<control>>
participant ":Grado" as Entity <<entity>>

note over Boundary : <<abstracto>> Invocado desde CU-03: importarConfiguracionGlobal

[-> Boundary : subirFichero(ficheroJSON)
activate Boundary

Boundary -> Control : importarGrados(listaGrados)
activate Control

Control -> Entity : guardarOActualizar(grado)
activate Entity
Entity --> Control : grado
deactivate Entity

Control --> Boundary : confirmacion
deactivate Control

[<- Boundary : confirmacion
deactivate Boundary

@enduml
