@startuml editarAsignatura-analisis
skinparam linetype polyline

actor Docente
package editarAsignatura as "editarAsignatura()" {
    rectangle #629EF9 SubjectEditView
    rectangle #b5bd68 SubjectController
    rectangle #F2AC4E Subject
    rectangle #F2AC4E Grade
    rectangle #F2AC4E Student
    rectangle #F2AC4E Question
}

Docente -r-> SubjectEditView: modificarDatos(datos)
SubjectEditView -d-> SubjectController: guardar(datos)
SubjectController --> Subject: actualizar(datos)

Docente --> SubjectEditView: verBateriaPreguntas()
SubjectEditView --> SubjectController: abrirPreguntas()

Docente --> SubjectEditView: eliminarAsignatura()
SubjectEditView --> SubjectController: eliminar()
SubjectController --> Subject: delete()

@enduml