@startuml importarPreguntas-analisis
skinparam linetype polyline

actor Docente
package importarPreguntas as "importarPreguntas()" {
    rectangle #629EF9 QuestionImportView
    rectangle #b5bd68 QuestionImportController
    rectangle #F2AC4E Question
    rectangle #F2AC4E Subject
    rectangle #F2AC4E Topic
}

Docente -r-> QuestionImportView: seleccionarOrigen(archivo)
QuestionImportView -d-> QuestionImportController: analizarArchivo(archivo)
QuestionImportController --> Question: crearInstancia()
QuestionImportController --> QuestionImportView: mostrarResumen()

Docente --> QuestionImportView: confirmarImportacion()
QuestionImportView --> QuestionImportController: persistirPreguntas()
QuestionImportController --> Question: guardar()

@enduml