# CONFIGURACIÓN DEL SERVIDOR
server.port=9090

# CONFIGURACIÓN DE LA BASE DE DATOS (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/jorgestor_db
spring.datasource.username=postgres
spring.datasource.password=ace

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# MANTENIMIENTO (Poner a false tras el primer arranque exitoso)
jorgestor.db.clean-on-startup=false
