@startuml exportarAsignaturas-analisis
skinparam linetype polyline

actor Docente
package exportarAsignaturas as "exportarAsignaturas()" {
    rectangle #629EF9 VistaExportacionAsignaturas
    rectangle #b5bd68 ControladorExportacionAsignaturas
    rectangle #F2AC4E Asignatura
}

Docente -r-> VistaExportacionAsignaturas: solicitarExportacion()
VistaExportacionAsignaturas -d-> ControladorExportacionAsignaturas: procesarExportacion()
ControladorExportacionAsignaturas --> Asignatura: obtenerDatosAsignaturas()
ControladorExportacionAsignaturas --> VistaExportacionAsignaturas: devolverFichero()
VistaExportacionAsignaturas --> Docente: descargarFichero()

@enduml
