@startuml exportarAsignaturas-analisis
skinparam linetype polyline

actor Docente
package exportarAsignaturas as "exportarAsignaturas()" {
    rectangle #629EF9 SubjectExportView
    rectangle #b5bd68 SubjectExportController
    rectangle #F2AC4E Subject
}

Docente -r-> SubjectExportView: solicitarExportacion()
SubjectExportView -d-> SubjectExportController: procesarExportacion()
SubjectExportController --> Subject: obtenerDatosAsignaturas()
SubjectExportController --> SubjectExportView: devolverFichero()
SubjectExportView --> Docente: descargarFichero()

@enduml
