@startuml
skinparam linetype polyline

class "SubjectExportView" <<boundary>>
class "SubjectExportController" <<control>>
class "Subject" <<entity>>

SubjectExportView -> SubjectExportController : procesarExportacion()
SubjectExportController -> Subject : obtenerDatosAsignaturas()
@enduml
