@startuml generarExamenes-analisis
skinparam linetype polyline

actor Docente
package generarExamenes as "generarExamenes()" {
    rectangle #629EF9 GenerationView
    rectangle #b5bd68 GenerationController
    rectangle #F2AC4E Subject
    rectangle #F2AC4E Topic
    rectangle #F2AC4E Question
    rectangle #F2AC4E Exam
}

Docente -r-> GenerationView: seleccionarAsignatura()
GenerationView -d-> GenerationController: obtenerTemas(asignatura)
GenerationController --> Subject: getTemas()
Subject --> Topic

Docente --> GenerationView: generarExamenes(parametros)
GenerationView --> GenerationController: generar(parametros)
GenerationController --> Question: filtrarPorParametros(parametros)
GenerationController --> Exam: crearExamen(preguntas)

@enduml