@startuml exportarPreguntas-analisis
skinparam linetype polyline

actor Docente
package exportarPreguntas as "exportarPreguntas()" {
    rectangle #629EF9 VistaExportacionPreguntas
    rectangle #b5bd68 ControladorExportacion
    rectangle #F2AC4E Pregunta
    rectangle #F2AC4E Respuesta
}

Docente -r-> VistaExportacionPreguntas: exportarPreguntas()
VistaExportacionPreguntas -d-> ControladorExportacion: recopilarPreguntas()
ControladorExportacion --> Pregunta: obtenerPreguntas()
ControladorExportacion --> Respuesta: obtenerRespuestas(pregunta)
ControladorExportacion --> VistaExportacionPreguntas: notificarExito()

@enduml