@startuml cu08-exportarPreguntas-analisis-secuencia
title Diagrama de Secuencia (Análisis) - CU-08: Exportar Preguntas

participant ":VistaExportacionPreguntas" as Boundary <<boundary>>
participant ":ControladorExportacion" as Control <<control>>
participant ":Pregunta" as Entity <<entity>>

note over Boundary : <<abstracto>> Invocado desde CU-04: exportarConfiguracionGlobal

[-> Boundary : solicitarExportacion()
activate Boundary

Boundary -> Control : exportarPreguntas()
activate Control

Control -> Entity : obtenerTodasConRespuestas()
activate Entity
Entity --> Control : listaPreguntas
deactivate Entity

Control --> Boundary : ficheroJSON
deactivate Control

[<- Boundary : ficheroJSON
deactivate Boundary

@enduml
