@startuml eliminarDocente-analisis
skinparam linetype polyline

actor AdministradorInstitucional
package eliminarDocente as "eliminarDocente()" {
    rectangle #629EF9 DocenteDeleteView
    rectangle #b5bd68 DocenteController
    rectangle #F2AC4E Docente
}

AdministradorInstitucional -r-> DocenteDeleteView: solicitarEliminar()
DocenteDeleteView --> Docente: getDatos()
AdministradorInstitucional --> DocenteDeleteView: confirmarEliminar()
DocenteDeleteView -d-> DocenteController: eliminarDocente()
DocenteController --> Docente: delete()

@enduml
