@startuml crearAsignatura-analisis
skinparam linetype polyline

actor Docente
package crearAsignatura as "crearAsignatura()" {
    rectangle #629EF9 SubjectCreationView
    rectangle #b5bd68 SubjectController
    rectangle #F2AC4E Subject
    rectangle #F2AC4E QuestionBank
    rectangle #F2AC4E Student
    rectangle #F2AC4E Grade
}

Docente -r-> SubjectCreationView: solicitarCreacion()
Docente --> SubjectCreationView: introducirDatos(nombre, codigo, curso)
SubjectCreationView -d-> SubjectController: crearAsignatura(datos)
SubjectController --> Subject: inicializar(datos)
SubjectController --> QuestionBank: crearBateria()
SubjectController --> SubjectCreationView: notificarExitoYRedirigir()

@enduml