@startuml verDocentes-analisis
skinparam linetype polyline

actor AdministradorInstitucional
package verDocentes as "verDocentes()" {
    rectangle #629EF9 DocenteListView
    rectangle #b5bd68 DocenteController
    rectangle #F2AC4E Docente
}

AdministradorInstitucional -r-> DocenteListView: solicitarVerDocentes()
DocenteListView -d-> DocenteController: obtenerDocentes()
DocenteController --> Docente: consultarTodos()

AdministradorInstitucional --> DocenteListView: aplicarFiltro(criterios)
DocenteListView --> DocenteController: filtrar(criterios)
DocenteController --> Docente: consultar(criterios)

@enduml
