@startuml cu20-verPreguntas-analisis-secuencia
title Diagrama de Secuencia (Análisis) - CU-20: Ver Preguntas

actor "Docente" as Actor
participant ":QuestionListView" as Boundary <<boundary>>
participant ":QuestionController" as Control <<control>>
participant ":Question" as Entity <<entity>>

Actor -> Boundary : solicitarListado()
activate Boundary

Boundary -> Control : obtenerPreguntas()
activate Control

Control -> Entity : consultarTodas()
activate Entity
Entity --> Control : listaPreguntas
deactivate Entity

Control --> Boundary : listaPreguntas
deactivate Control

Boundary --> Actor : mostrarListado(preguntas)
deactivate Boundary

@enduml
