@startuml verAlumnos-analisis
skinparam linetype polyline

actor Docente
package verAlumnos as "verAlumnos()" {
    rectangle #629EF9 VistaListaAlumnos
    rectangle #b5bd68 ControladorAlumnos
    rectangle #F2AC4E Alumno
}

Docente -r-> VistaListaAlumnos: solicitarVerAlumnos()
VistaListaAlumnos -d-> ControladorAlumnos: cargarAlumnos()
ControladorAlumnos --> Alumno: consultarTodos()

Docente --> VistaListaAlumnos: aplicarFiltro(criterios)
VistaListaAlumnos --> ControladorAlumnos: filtrar(criterios)
ControladorAlumnos --> Alumno: consultar(criterios)

@enduml