@startuml importarAsignaturas-analisis
skinparam linetype polyline

actor Docente
package importarAsignaturas as "importarAsignaturas()" {
    rectangle #629EF9 VistaImportacionAsignaturas
    rectangle #b5bd68 ControladorImportacionAsignaturas
    rectangle #F2AC4E Asignatura
}

Docente -r-> VistaImportacionAsignaturas: solicitarImportar()
VistaImportacionAsignaturas --> Docente: pedirArchivo()
Docente --> VistaImportacionAsignaturas: proporcionarArchivo()
VistaImportacionAsignaturas --> ControladorImportacionAsignaturas: validarDatos()
ControladorImportacionAsignaturas --> Asignatura: verificarExistencia()
VistaImportacionAsignaturas --> Docente: mostrarResumen()
Docente --> VistaImportacionAsignaturas: confirmarImportacion()
VistaImportacionAsignaturas -d-> ControladorImportacionAsignaturas: importar()
ControladorImportacionAsignaturas --> Asignatura: save()

@enduml