@startuml importarAsignaturas-analisis
skinparam linetype polyline

note "<<abstracto>>\nInvocado desde CU-03: importarConfiguracionGlobal" as N1
package importarAsignaturas as "importarAsignaturas()" {
    rectangle #629EF9 VistaImportacionAsignaturas
    rectangle #b5bd68 ControladorImportacionAsignaturas
    rectangle #F2AC4E Asignatura
}

VistaImportacionAsignaturas -d-> ControladorImportacionAsignaturas: importarAsignaturas(listaAsignaturas)
ControladorImportacionAsignaturas --> Asignatura: guardarOActualizar(asignatura)
ControladorImportacionAsignaturas --> VistaImportacionAsignaturas: confirmacion

@enduml