@startuml cu38-importarAsignaturas-analisis-secuencia
title Diagrama de Secuencia (Análisis) - CU-38: Importar Asignaturas

participant ":VistaImportacionAsignaturas" as Boundary <<boundary>>
participant ":ControladorImportacionAsignaturas" as Control <<control>>
participant ":Asignatura" as Entity <<entity>>

note over Boundary : <<abstracto>> Invocado desde CU-03: importarConfiguracionGlobal

[-> Boundary : subirFichero(ficheroJSON)
activate Boundary

Boundary -> Control : importarAsignaturas(listaAsignaturas)
activate Control

Control -> Entity : guardarOActualizar(asignatura)
activate Entity
Entity --> Control : asignatura
deactivate Entity

Control --> Boundary : confirmacion
deactivate Control

[<- Boundary : confirmacion
deactivate Boundary

@enduml
