@startuml cancelarGeneracion-analisis
skinparam linetype polyline

actor Docente
package cancelarGeneracion as "cancelarGeneracion()" {
    rectangle #629EF9 VistaCancelacionGeneracion
    rectangle #b5bd68 ControladorGeneracionExamen
    rectangle #F2AC4E Examen
}

Docente -r-> VistaCancelacionGeneracion: cancelarGeneracion()
VistaCancelacionGeneracion --> Docente: pedirConfirmacion()
Docente --> VistaCancelacionGeneracion: confirmar()
VistaCancelacionGeneracion -d-> ControladorGeneracionExamen: descartarGeneracion()
ControladorGeneracionExamen --> Examen: delete()

@enduml