@startuml exportarGrados-analisis
skinparam linetype polyline

actor Docente
package exportarGrados as "exportarGrados()" {
    rectangle #629EF9 GradeExportView
    rectangle #b5bd68 GradeExportController
    rectangle #F2AC4E Grade
}

Docente -r-> GradeExportView: solicitarExportacion()
GradeExportView -d-> GradeExportController: procesarExportacion()
GradeExportController --> Grade: obtenerDatosGrados()
GradeExportController --> GradeExportView: devolverFichero()
GradeExportView --> Docente: descargarFichero()

@enduml
