@startuml cu41-exportarGrados-analisis-secuencia
title Diagrama de Secuencia (Análisis) - CU-41: Exportar Grados

actor "Docente" as Actor
participant ":VistaExportacionGrados" as Boundary <<boundary>>
participant ":ControladorExportacionGrados" as Control <<control>>
participant ":Grado" as Entity <<entity>>

Actor -> Boundary : solicitarExportacion()
activate Boundary

Boundary -> Control : exportarGrados()
activate Control

Control -> Entity : obtenerTodos()
activate Entity
Entity --> Control : listaGrados
deactivate Entity

Control --> Boundary : ficheroJSON
deactivate Control

Boundary --> Actor : descargarFichero(ficheroJSON)
deactivate Boundary

@enduml
