@startuml cu31-cerrarSesion-analisis-secuencia
title Diagrama de Secuencia (Análisis) - CU-31: Cerrar Sesión

actor "Usuario" as Actor
participant ":SessionView" as Boundary <<boundary>>
participant ":LogoutController" as Control <<control>>
participant ":UserSession" as Entity <<entity>>

Actor -> Boundary : solicitarCerrarSesion()
activate Boundary

Boundary -> Control : cerrarSesion()
activate Control

Control -> Entity : invalidar()
activate Entity
Entity --> Control : ok
deactivate Entity

Control --> Boundary : sesionCerrada
deactivate Control

Boundary --> Actor : redirigirAlLogin()
deactivate Boundary

@enduml
