@startuml cerrarSesion-analisis
skinparam linetype polyline

actor Usuario
package cerrarSesion as "cerrarSesion()" {
    rectangle #629EF9 SessionView
    rectangle #b5bd68 LogoutController
    rectangle #F2AC4E UserSession
}

Usuario -r-> SessionView: solicitarCierre()
SessionView --> Usuario: pedirConfirmacion()
Usuario --> SessionView: confirmarCierre()
SessionView -d-> LogoutController: cerrarSesion()
LogoutController --> UserSession: invalidar()

@enduml