@startuml crearAlumno-analisis
skinparam linetype polyline

actor Docente
package crearAlumno as "crearAlumno()" {
    rectangle #629EF9 StudentCreationView
    rectangle #b5bd68 StudentController
    rectangle #F2AC4E Student
}

Docente -r-> StudentCreationView: solicitarCreacion()
Docente --> StudentCreationView: introducirDatos(nombre, apellidos, dni)
StudentCreationView -d-> StudentController: crearAlumno(datos)
StudentController --> Student: inicializar(datos)
StudentController --> StudentCreationView: notificarExitoYRedirigir()

@enduml