@startuml editarPregunta-analisis
skinparam linetype polyline

actor Docente
package editarPregunta as "editarPregunta()" {
    rectangle #629EF9 QuestionEditView
    rectangle #b5bd68 QuestionController
    rectangle #F2AC4E Question
    rectangle #F2AC4E Subject
    rectangle #F2AC4E Topic
    rectangle #F2AC4E Answer
}

Docente -r-> QuestionEditView: modificarCampos(datos)
QuestionEditView -d-> QuestionController: guardarCambios(datos)
QuestionController --> Question: actualizar(datos)
QuestionController --> Answer: actualizarRespuestas(respuestas)

Docente --> QuestionEditView: eliminarPregunta()
QuestionEditView --> QuestionController: eliminar()
QuestionController --> Question: delete()

@enduml