@startuml exportarConfiguracionGlobal-analisis
skinparam linetype polyline

actor Docente
package exportarConfiguracionGlobal as "exportarConfiguracionGlobal()" {
    rectangle #629EF9 VistaExportConfigGlobal
    rectangle #b5bd68 ControladorExportacion
    rectangle #F2AC4E Alumno
    rectangle #F2AC4E Grado
    rectangle #F2AC4E Asignatura
    rectangle #F2AC4E Pregunta
}

Docente -r-> VistaExportConfigGlobal: exportarConfiguracion(opciones)
VistaExportConfigGlobal -d-> ControladorExportacion: recopilarDatos(opciones)

ControladorExportacion --> Alumno: obtenerTodos()
ControladorExportacion --> Grado: obtenerTodos()
ControladorExportacion --> Asignatura: obtenerTodos()
ControladorExportacion --> Pregunta: obtenerTodos()

ControladorExportacion --> VistaExportConfigGlobal: mostrarConfirmacion()
Docente --> VistaExportConfigGlobal: confirmarExportacion()
VistaExportConfigGlobal --> ControladorExportacion: generarArchivo()

@enduml