@startuml crearDocente-analisis
skinparam linetype polyline

actor AdministradorInstitucional
package crearDocente as "crearDocente()" {
    rectangle #629EF9 DocenteCreationView
    rectangle #b5bd68 DocenteController
    rectangle #F2AC4E Docente
}

AdministradorInstitucional -r-> DocenteCreationView: solicitarCreacion()
AdministradorInstitucional --> DocenteCreationView: proporcionarDatos(dni, nombre, apellidos, usuario, email, password)
DocenteCreationView -d-> DocenteController: crearDocente(datos)
DocenteController --> Docente: validarNoDuplicado(dni, usuario)
DocenteController --> Docente: inicializar(datos)
DocenteController --> DocenteCreationView: notificarExitoYRedirigir()

@enduml
