@startuml crearDocente-analisis
skinparam linetype polyline

actor AdministradorInstitucional
package crearDocente as "crearDocente()" {
    rectangle #629EF9 DocentCreationView
    rectangle #b5bd68 DocentController
    rectangle #F2AC4E Docent
}

AdministradorInstitucional -r-> DocentCreationView: solicitarCreacion()
AdministradorInstitucional --> DocentCreationView: proporcionarDatos(dni, nombre, apellidos, usuario, email, password)
DocentCreationView -d-> DocentController: crearDocente(datos)
DocentController --> Docent: validarNoDuplicado(dni, usuario)
DocentController --> Docent: inicializar(datos)
DocentController --> DocentCreationView: notificarExitoYRedirigir()

@enduml